-- require("lualine").setup({
-- 	options = {
-- 		theme = "tokyonight",
-- 	},
-- 	sections = { lualine_c = { require("auto-session.lib").current_session_name } },
-- })
-- require("leap").create_default_mappings()
--
--
-- local capabilities = vim.lsp.protocol.make_client_capabilities()
-- capabilities.textDocument.foldingRange = {
--     dynamicRegistration = false,
--     lineFoldingOnly = true
-- }
-- local language_servers = require("lspconfig").util.available_servers() -- or list servers manually like {'gopls', 'clangd'}
-- for _, ls in ipairs(language_servers) do
--     require('lspconfig')[ls].setup({
--         capabilities = capabilities
--         -- you can add other fields for setting up lsp server in this table
--     })
-- end
-- require('ufo').setup()
-- vim: ts=2 sts=2 sw=2 et
